# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd "/epics/ioc"
dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

# simDetectorConfig(portName, maxSizeX, maxSizeY, dataType, maxBuffers, maxMemory)
simDetectorConfig("DET.DET", 1280, 1024, 1, 50, 0)
# NDPvaConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, pvName, maxBuffers, maxMemory, priority, stackSize)
NDPvaConfigure("DET.PVA", 2, 0, "DET.DET", 0, BL01T-EA-TST-02:PVA:OUTPUT, 0, 0, 0, 0)
startPVAServer

dbLoadRecords $(RUNTIME_DIR)/ioc.db
iocInit

